# Generated by Django 3.2.6 on 2023-01-13 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_auto_20230113_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=250, verbose_name='detalle_trabajo')),
                ('fecha', models.DateField(verbose_name='fecha_trabajo')),
                ('fecha_receta', models.DateField(null=True, verbose_name='fecha_receta_trabajo')),
                ('tarea', models.CharField(help_text='Tarea o actividad extra realizada sobre el trabajo', max_length=250, verbose_name='tarea_trabajo')),
                ('observacion', models.CharField(max_length=1000, verbose_name='observacion_trabajo')),
                ('od_lejos_esf', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_lejos_esferico')),
                ('od_lejos_cil', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_lejos_cilindrico')),
                ('od_lejos_eje', models.IntegerField(null=True, verbose_name='ojo_derecho_lejos_eje')),
                ('od_ad', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_adicion')),
                ('od_cerca_esf', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_cerca_esferico')),
                ('od_cerca_cil', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_cerca_cilindrico')),
                ('od_cerca_eje', models.IntegerField(null=True, verbose_name='ojo_derecho_cerca_eje')),
                ('oi_lejos_esf', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_lejos_esferico')),
                ('oi_lejos_cil', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_lejos_cilindrico')),
                ('oi_lejos_eje', models.IntegerField(null=True, verbose_name='ojo_izquierdo_lejos_eje')),
                ('oi_ad', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_adicion')),
                ('oi_cerca_esf', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_cerca_esferico')),
                ('oi_cerca_cil', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_cerca_cilindrico')),
                ('oi_cerca_eje', models.IntegerField(null=True, verbose_name='ojo_izquierdo_cerca_eje')),
                ('armazon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazon_trabajo', to='base.armazon', verbose_name='armazon')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_trabajo', to='base.doctor', verbose_name='doctor')),
                ('lente_con_tratamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_con_tratamiento_trabajo', to='base.lentetratamiento', verbose_name='lente_con_tratamiento')),
                ('obra_social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obra_social_trabajo', to='base.obrasocial', verbose_name='obra_social')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
    ]
