# Generated by Django 3.2.6 on 2023-01-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('ciudad', models.CharField(max_length=60, verbose_name='ciudad')),
            ],
        ),
    ]
